language: python
python:
  - "3.7"
install:
  - pip install poetry
  - make install-dev

jobs:
    include:
        - stage: lint
          script: make lint
        - stage: test
          script: make test